### ISSUE TITLE
Linking from CDN does not work - Cann't find variable require

### ISSUE THREAD

**Issue by balazsnemeth** [FRSource/FRS-hide-scrollbar#2]
Linking from CDN does not work, it throw an error "Cann't find variable require"

<script type="text/javascript" src="https://unpkg.com/frs-hide-scrollbar"></script>

<img width="926" alt="Screenshot 2019-04-25 13 25 11" src="https://user-images.githubusercontent.com/2070044/56732428-93c08d00-675d-11e9-8222-2fc8c531a497.png">

**Comment by FRSgit** [comment]
Hi @balazsnemeth,

Thanks for submitting an issue - you're right, there is a bug in package.json for unpkg.
Unpkg link should point to either:
(vanilla js build)
`https://unpkg.com/frs-hide-scrollbar@0.1.8/dist/FRS-hide-scrollbar.vanilla.js`
(for bundle-ready build)
`https://unpkg.com/frs-hide-scrollbar@0.1.8/dist/FRS-hide-scrollbar.js`

Please use one of these above until I fix it (probably later today).

**Comment by FRSgit** [comment]
@balazsnemeth Hey, this issue got fixed and `unpkg` refreshed their cached url response, so can you please double check if url `https://unpkg.com/frs-hide-scrollbar` now works for you correctly?

**Comment by FRSgit** [comment]
Seems like everything is working like it should, closing.
